Allow rpmdb to manage files on mounted container filesystems
Running `rpmdb --rebuilddb --root=<container-mount-path>` on a mounted
container filesystem fails with the following error when SELinux is
enforcing:

  error: can't create transaction lock on
  .../merged/var/lib/rpm/.rpm.lock (Permission denied)

The AVC denial is:

  avc: denied { search } for comm="rpmdb"
  scontext=unconfined_u:unconfined_r:rpmdb_t:s0-s0:c0.c1023
  tcontext=system_u:object_r:container_var_lib_t:s0 tclass=dir

The rpmdb_t domain needs access to:
- container_var_lib_t dirs (to traverse /var/lib/containers/storage/)
- container_ro_file_t dirs/files (to traverse overlay directories)
- container_file_t dirs/files (to manage RPM database in the merged fs)

Additionally, rpmdb_t needs the object identity change exemption to
satisfy the UBAC constraint when creating files/dirs. Container
filesystems are created by the container runtime with user identity
system_u, but rpmdb is invoked from an unconfined user session
(unconfined_u). Without the exemption, the user identity mismatch
causes constraint violations on create operations. The map permission
on container_file_t files is also needed for sqlite shared memory
mapping during database operations.

Fixes: RHEL-58185

Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>