Revert "container: label /run/user/*/crun as container_var_run_t"
This reverts commit ae3532b16fea ("container: label /run/user/*/crun
as container_var_run_t") as it breaks basic Podman operation with
pasta(1) (default rootless back-end):

  Error: setting up Pasta: pasta failed with exit code 1:
  Couldn't open PID file /run/user/1000/containers/networks/rootless-netns/rootless-netns-conn.pid: Permission denied

A solution is being worked on, but it's not quite ready yet, see:

  https://github.com/containers/container-selinux/pull/405

in the meantime, revert this to avoid widespread breakage for users.

Link: https://github.com/containers/container-selinux/pull/405
Signed-off-by: Stefano Brivio <sbrivio@redhat.com>